### ISSUE TITLE
getTicker()

### ISSUE THREAD

**Issue by caa1982** [tiaanduplessis/coinmarketcap-api#13]
I think getTicker({limit: 1, currency: 'bitcoin'}) only work with bitcoin... 

Also any Chance to add ticker?

**Comment by abhinavk99** [comment]
I think the API wrapper needs to be changed, because at https://coinmarketcap.com/api/, you can see that there are two different ticker endpoints, one that uses the rank of the coin and one that uses the id of the coin from the listings endpoint, which is a breaking change.

And about adding tickers, that's not really possible because the wrapper just takes data from CoinMarketCap, so you'll have to bring it up with them if you want a ticker added to their database.

**Comment by caa1982** [comment]
yep! first you need to get the listing from 
https://api.coinmarketcap.com/v2/listings/

then loop through it and make another call to CMC

I will take a look at it over the w/e if I have time. Unless someone can do it before

**Comment by abhinavk99** [comment]
I'll work on it later today most likely.

**Comment by abhinavk99** [comment]
I worked on this in #14. 

Your code might not work anymore because according to https://coinmarketcap.com/api/, the start and limit parameters are not to be used when a currency is passed in as a parameter.

Also, I made it so you can either pass in the currency symbol (e.g. BTC) or its ID from the listings endpoint. I made it based on the symbol and not the name because it will be more accurate than the name, which spaces and hyphens could mess with.
